### PR TITLE
enh: leverage buffered IO

### PR DESCRIPTION
**Pull request by davidecavestro**
Still measure progress intercepting `read` method invocations

### CODE REVIEW

**Comment by rogosprojects** [comment]
Without the `--follow` flag, logs will print the "streaming spinner" still
image

**Comment by davidecavestro** [comment]
> Without the `--follow` flag, logs will print the "streaming spinner" still image

I'd say this also happens in master, as there's no condition on whether it should be shown:  https://github.com/rogosprojects/klogs/blob/52aebab1cb9dcdd825117d1c288022ff2addd543/cmd/root.go#L320-L330

That said, if you want I can show it just when the `follow` switch is on.

**Comment by rogosprojects** [comment]
Great! Testing with large cluster. 
Merging if OK.

**Comment by davidecavestro** [comment]
Ok, please also note that - in case you consider overkilling updating the size at every read - the MeteredReader could be re-absorded, and leverage a separate thread measuring/showing the file size i.e. every 1 sec.

**Comment by rogosprojects** [comment]
Indeed, the function that checks the size could be async and should always prints size (even without `--follow` )

**Comment by davidecavestro** [comment]
IMHO this PR could be considered as the minimum change to leverage bufio and avoid logic related to chunking.
The size is updated as often as before (at the cost of decorating the reader to intercept buffered reads).
Then another PR could replace the logic based on the amount of read bytes with its couterpart based on file size (if it's worth it).

**Pull request merged**
